---
- name: Check if puppet repo is already configured.
  stat: path={{ puppet_repofile_path }}
  register: puppet_repofile_result

- name: Install puppet repo.
  yum:
    name: "{{ puppet_repo_url }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: not puppet_repofile_result.stat.exists

- name: Import puppet GPG keys.
  rpm_key:
    key: "{{ item }}"
    state: present
  with_items: "{{ puppet_repo_gpg_key_urls }}"
  when: not puppet_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: Ensure puppet is installed.
  yum:
    name: "{{ puppet_package_name }}"
    state: "installed"

- name: Check if puppet csr attributes yaml file is already configured.
  stat: path={{ puppet_csr_attr_yaml }}
  register: puppet_csrfile_yaml_result

- name: Setup csr_attributes.yaml
  template:
    src="csr_attributes.yaml.j2"
    dest="{{ puppet_csr_attr_yaml }}"
    owner="root"
    group="root"
    mode="0400"

- name: Setup puppet.conf
  template:
    src="puppet.conf.j2"
    dest="{{ puppet_conf_path }}"
    owner="root"
    group="root"
    mode="0440"

- name: Run puppet.
  command: >
    /opt/puppetlabs/bin/puppet
    agent
    -t
  register: puppet_run_result
  retries: 1
  until: puppet_run_result.rc == 0
